# main text of home
name: Jashan Sudan
bio: Hello! My name is Jashan Sudan and I am a 4th year Bachelor of Computing Candidate at Queen's University. I enjoy solving problems, playing with new technologies and trying new things!


# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/jashansudan.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: /Résumé.pdf

url: https://jashansudan.github.io
# your url: http://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1


# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: jashansudan
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
linkedin: jashansudan
# vimeo: myvimeo
email: jashansudan@gmail.com


# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"



# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com
